apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
type: Opaque
stringData:
  db-url: "postgresql://youruser:yourpass@postgres-service:5432/tododb"
  jwt-secret: "wLKEeKKCj3IN18kIKS6QYdYVl-oNksKhy5llqgJBFNw"
